"""Validated request-header helpers shared by typed resource methods."""

from __future__ import annotations

from parampilot.serialization import idempotency_key, required_header


def mutation_headers(
    *,
    idempotency: str | None,
    if_match: str | None = None,
) -> dict[str, str]:
    """Build headers for an idempotent optional-precondition mutation.

    Args:
        idempotency: Optional caller-supplied idempotency key.
        if_match: Optional required resource revision.

    Returns:
        Validated mutation headers. A missing idempotency key is generated by
        the transport once for the complete retry sequence.

    """
    headers: dict[str, str] = {}
    if idempotency is not None:
        headers["Idempotency-Key"] = idempotency_key(idempotency)
    if if_match is not None:
        headers["If-Match"] = required_header(if_match, label="if_match")
    return headers


def revalidation_headers(if_none_match: str | None) -> dict[str, str]:
    """Build an optional conditional-read header.

    Args:
        if_none_match: Optional cached artifact validator.

    Returns:
        Empty or validated conditional header mapping.

    """
    if if_none_match is None:
        return {}
    return {"If-None-Match": required_header(if_none_match, label="if_none_match")}
