"""Transactional orchestration for ParamPilot public contract artifacts."""

from __future__ import annotations

import importlib.metadata
import subprocess
import tempfile
from pathlib import Path

from parampilot_codegen.artifacts import (
    artifact_differences,
    load_json_object,
    publish_artifacts,
    render_json,
)
from parampilot_codegen.configuration import (
    CANONICAL_SCHEMA,
    COVERAGE_MANIFEST,
    GENERATED_OUTPUTS,
    GENERATOR_DISTRIBUTION,
    GENERATOR_VERSION,
    MODEL_EXPORTS_OUTPUT,
    MODEL_STUB_OUTPUT,
    MODELS_OUTPUT,
    OPERATIONS_OUTPUT,
    PACKAGE_ROOT,
    PROVENANCE_OUTPUT,
    model_generator_command,
)
from parampilot_codegen.coverage import validate_coverage
from parampilot_codegen.exports import (
    component_names,
    render_model_exports,
    render_model_stub,
)
from parampilot_codegen.manifest import build_provenance
from parampilot_codegen.normalization import normalize_schema_for_codegen
from parampilot_codegen.operations import build_operations_document


class ContractGenerationError(RuntimeError):
    """Raised when generation inputs, tools, outputs, or drift are invalid."""


def _write(root: Path, relative_path: Path, content: bytes) -> None:
    """Write one generated artifact inside a temporary tree.

    Args:
        root: Temporary artifact root.
        relative_path: Sanitized output path relative to ``root``.
        content: Exact generated bytes.

    """
    destination = root / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(content)


def _require_generator_version() -> None:
    """Require the exact qualified generator distribution version.

    Raises:
        ContractGenerationError: If the generator is absent or has drifted.

    """
    try:
        installed = importlib.metadata.version(GENERATOR_DISTRIBUTION)
    except importlib.metadata.PackageNotFoundError as error:
        raise ContractGenerationError(
            f"Install {GENERATOR_DISTRIBUTION}=={GENERATOR_VERSION} before generation"
        ) from error
    if installed != GENERATOR_VERSION:
        raise ContractGenerationError(
            f"Expected {GENERATOR_DISTRIBUTION}=={GENERATOR_VERSION}, found {installed}"
        )


def _generate_models(schema_path: Path, destination: Path) -> None:
    """Run the pinned Pydantic model generator without shell interpretation.

    Args:
        schema_path: Temporary canonical OpenAPI input.
        destination: Temporary generated Python output.

    Raises:
        ContractGenerationError: If model generation fails.

    """
    destination.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(  # noqa: S603 - fixed executable and trusted arguments
        model_generator_command(schema_path, destination),
        cwd=PACKAGE_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        diagnostic = result.stderr.strip() or result.stdout.strip()
        raise ContractGenerationError(f"Pydantic model generation failed: {diagnostic}")


def _generate_tree(schema_source: Path, output_root: Path) -> None:
    """Generate the complete contract tree from one exact schema source.

    Args:
        schema_source: Source artifact selected for this generation.
        output_root: Empty temporary tree receiving canonical and generated files.

    """
    canonical = output_root / CANONICAL_SCHEMA
    canonical.parent.mkdir(parents=True, exist_ok=True)
    canonical.write_bytes(schema_source.read_bytes())
    schema = load_json_object(canonical)
    coverage = load_json_object(PACKAGE_ROOT / COVERAGE_MANIFEST)
    operations = build_operations_document(schema)
    validate_coverage(coverage, operations)

    normalized_schema = output_root / "_normalized" / CANONICAL_SCHEMA.name
    normalized_bytes = render_json(normalize_schema_for_codegen(schema))
    _write(
        output_root,
        normalized_schema.relative_to(output_root),
        normalized_bytes,
    )
    _generate_models(normalized_schema, output_root / MODELS_OUTPUT)
    names = component_names(schema)
    _write(output_root, MODEL_EXPORTS_OUTPUT, render_model_exports(names))
    _write(output_root, MODEL_STUB_OUTPUT, render_model_stub(names))
    _write(output_root, OPERATIONS_OUTPUT, render_json(operations))
    provenance = build_provenance(
        schema,
        len(operations["operations"]),
        output_root,
        normalized_bytes,
    )
    _write(output_root, PROVENANCE_OUTPUT, render_json(provenance))


def run_generation(
    *, check: bool, schema_source: Path | None = None
) -> tuple[str, ...]:
    """Regenerate or verify every public contract artifact transactionally.

    Args:
        check: Compare temporary output without modifying committed files.
        schema_source: Optional authoritative handoff artifact. The committed
            public copy is used when omitted.

    Returns:
        Relative paths verified or published.

    Raises:
        ContractGenerationError: If inputs, tooling, generation, or drift fail.

    """
    _require_generator_version()
    selected_schema = schema_source or (PACKAGE_ROOT / CANONICAL_SCHEMA)
    if not selected_schema.is_file():
        raise ContractGenerationError(
            f"Schema source does not exist: {selected_schema}"
        )
    relative_paths = (CANONICAL_SCHEMA, *GENERATED_OUTPUTS)
    with tempfile.TemporaryDirectory(prefix="parampilot-contracts-") as temporary:
        generated_root = Path(temporary)
        _generate_tree(selected_schema, generated_root)
        if check:
            differences = artifact_differences(
                generated_root,
                PACKAGE_ROOT,
                relative_paths,
            )
            if differences:
                diagnostic = "\n".join(f"- {item}" for item in differences)
                raise ContractGenerationError(
                    "Generated contract drift detected; run "
                    "`uv run python -m parampilot_codegen`:\n"
                    f"{diagnostic}"
                )
        else:
            publish_artifacts(generated_root, PACKAGE_ROOT, relative_paths)
    return tuple(path.as_posix() for path in relative_paths)
