"""Drift and provenance tests for deterministic public contract generation."""

from __future__ import annotations

import ast
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

PACKAGE_ROOT = Path(__file__).resolve().parents[2]
CANONICAL_SCHEMA = PACKAGE_ROOT / "contracts" / "programmatic-openapi.json"
GENERATED_ROOT = PACKAGE_ROOT / "src" / "parampilot" / "generated"
PROVENANCE_PATH = GENERATED_ROOT / "provenance.json"
UPSTREAM_SCHEMA = (
    PACKAGE_ROOT.parent / "parampilot-backend" / "schemas" / "programmatic-openapi.json"
)


def _load_json(path: Path) -> dict[str, Any]:
    """Load a JSON object from ``path``.

    Args:
        path: JSON file to decode.

    Returns:
        Decoded top-level JSON object.

    """
    value = json.loads(path.read_text())
    assert isinstance(value, dict)
    return value


def _sha256(path: Path) -> str:
    """Return the lowercase SHA-256 digest for one file.

    Args:
        path: File whose exact bytes are hashed.

    Returns:
        Hexadecimal SHA-256 digest.

    """
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_public_schema_copy_matches_private_handoff_when_available() -> None:
    """The monorepo copy must exactly match the authoritative backend artifact."""
    if not UPSTREAM_SCHEMA.is_file():
        pytest.skip("private backend source is intentionally absent")

    assert CANONICAL_SCHEMA.read_bytes() == UPSTREAM_SCHEMA.read_bytes()


def test_provenance_hashes_every_contract_input_and_generated_output() -> None:
    """The sanitized manifest must make every generated byte set auditable."""
    provenance = _load_json(PROVENANCE_PATH)
    input_metadata = provenance["input"]
    outputs = provenance["outputs"]

    assert provenance["format_version"] == 1
    assert provenance["generator"] == {
        "distribution": "datamodel-code-generator",
        "options": {
            "formatters": ["builtin"],
            "openapi_scopes": ["schemas"],
            "remote_refs": False,
            "root_model_sequence_interface": True,
            "schema_adapter": "union-constraints-v1",
            "schema_version": "3.1",
            "schema_version_mode": "strict",
        },
        "preset": "practical-py310-20260619",
        "target_pydantic": "2.12",
        "target_python": "3.10",
        "version": "0.68.1",
    }
    assert input_metadata["path"] == "contracts/programmatic-openapi.json"
    assert input_metadata["sha256"] == _sha256(CANONICAL_SCHEMA)
    assert input_metadata["bytes"] == CANONICAL_SCHEMA.stat().st_size
    assert input_metadata["paths"] == 34
    assert input_metadata["operations"] == 39
    assert input_metadata["schemas"] == 228

    from parampilot_codegen.artifacts import render_json
    from parampilot_codegen.normalization import normalize_schema_for_codegen

    normalized = render_json(normalize_schema_for_codegen(_load_json(CANONICAL_SCHEMA)))
    assert input_metadata["normalized_sha256"] == hashlib.sha256(normalized).hexdigest()
    assert input_metadata["normalized_bytes"] == len(normalized)

    for metadata in outputs.values():
        output_path = PACKAGE_ROOT / metadata["path"]
        assert output_path.is_file()
        assert metadata["sha256"] == _sha256(output_path)
        assert metadata["bytes"] == output_path.stat().st_size


def test_generation_check_reproduces_all_committed_outputs() -> None:
    """The public check command must regenerate to temporary files with no drift."""
    result = subprocess.run(
        [sys.executable, "-m", "parampilot_codegen", "--check"],
        cwd=PACKAGE_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Contract artifacts are current" in result.stdout


def test_drift_comparison_reports_changed_and_missing_generated_files(
    tmp_path: Path,
) -> None:
    """The comparison primitive must identify both stale and absent artifacts.

    Args:
        tmp_path: Pytest-managed scratch directory.

    """
    from parampilot_codegen.artifacts import artifact_differences

    expected_root = tmp_path / "expected"
    actual_root = tmp_path / "actual"
    expected_root.mkdir()
    actual_root.mkdir()
    (expected_root / "changed.txt").write_text("expected\n")
    (actual_root / "changed.txt").write_text("stale\n")
    (expected_root / "missing.txt").write_text("required\n")

    differences = artifact_differences(
        expected_root,
        actual_root,
        (Path("changed.txt"), Path("missing.txt")),
    )

    assert differences == (
        "changed generated artifact: changed.txt",
        "missing generated artifact: missing.txt",
    )


def test_codegen_normalization_moves_union_constraints_without_mutating_input() -> None:
    """The adapter must prevent duplicate RootModel constraints losslessly."""
    from parampilot_codegen.normalization import normalize_schema_for_codegen

    source = {
        "properties": {
            "bounds": {
                "anyOf": [
                    {"items": {"type": "number"}, "type": "array"},
                    {"type": "null"},
                ],
                "maxLength": 2,
                "minLength": 2,
            }
        }
    }

    normalized = normalize_schema_for_codegen(source)

    original_bounds = source["properties"]["bounds"]
    normalized_bounds = normalized["properties"]["bounds"]
    assert original_bounds["minLength"] == 2
    assert "minLength" not in normalized_bounds
    assert "maxLength" not in normalized_bounds
    assert normalized_bounds["anyOf"][0]["minLength"] == 2
    assert normalized_bounds["anyOf"][0]["maxLength"] == 2
    assert normalized_bounds["anyOf"][1] == {"type": "null"}


def test_generated_files_have_sanitized_provenance_and_public_imports() -> None:
    """Generated source must contain no private path, import, secret, or remote ref."""
    models_path = GENERATED_ROOT / "models.py"
    source = models_path.read_text()
    schema_text = CANONICAL_SCHEMA.read_text()
    forbidden_text = (
        "/home/",
        "C:\\",
        "parampilot_backend",
        "parampilot_worker",
        "Authorization:",
        "git+ssh",
    )

    assert source.startswith("# @generated by datamodel-codegen:")
    assert "#   filename:  programmatic-openapi.json" in source.splitlines()[:3]
    assert not [item for item in forbidden_text if item in source]
    assert not [item for item in forbidden_text if item in schema_text]
    schema = json.loads(schema_text)
    remote_references: list[str] = []
    pending: list[Any] = [schema]
    while pending:
        value = pending.pop()
        if isinstance(value, dict):
            reference = value.get("$ref")
            if isinstance(reference, str) and reference.startswith(
                ("http://", "https://")
            ):
                remote_references.append(reference)
            pending.extend(value.values())
        elif isinstance(value, list):
            pending.extend(value)
    assert remote_references == []

    tree = ast.parse(source, filename=str(models_path))
    import_roots: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            import_roots.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            import_roots.add(node.module.split(".")[0])
    assert import_roots <= {
        "__future__",
        "collections",
        "datetime",
        "enum",
        "typing",
        "uuid",
        "pydantic",
    }


def test_model_export_stub_covers_every_openapi_component() -> None:
    """Static model exports must exactly cover named OpenAPI components."""
    schema = _load_json(CANONICAL_SCHEMA)
    schemas = schema["components"]["schemas"]
    from parampilot.generated.model_exports import PUBLIC_MODEL_NAMES

    assert tuple(sorted(schemas)) == PUBLIC_MODEL_NAMES
    assert (PACKAGE_ROOT / "src" / "parampilot" / "models" / "__init__.pyi").is_file()


def test_every_generated_pydantic_model_rebuilds_against_public_names() -> None:
    """The complete generated graph must resolve without private runtime types."""
    from pydantic import BaseModel

    from parampilot.generated import models

    namespace = vars(models)
    model_classes = {
        value
        for value in namespace.values()
        if isinstance(value, type)
        and issubclass(value, BaseModel)
        and value is not BaseModel
    }

    assert len(model_classes) >= 490
    for model_class in model_classes:
        model_class.model_rebuild(force=True, _types_namespace=namespace)
